version: "3"

networks:
  my-net: 
    name: nginx-network
    driver: bridge

services:
  nginx:
    build: .
    image: "api"
    container_name: gate-way
    restart: always
    ports:
      - 7900:8000
    networks:
      - my-net
